using System;
using System.IO;
using System.Text;
using Core.AssetBundles.Management;
using UnityEditor;

namespace Editor.AssetBundle.Core
{
    /// <summary>
    /// 资源key生成器，避免硬编码字符串
    /// 所有资源文件名必须使用下划线 _ 分隔单词，例如：Hero_Icon.png、enemy_boss_data.asset
    /// </summary>
    public class AssetKeyGenerator
    {
        /// <summary>
        /// 根据资源目录生成资源键，保存至指定路径，运行时使用Key加载资源
        /// </summary>
        /// <param name="catalog"></param>
        /// <param name="savePath"></param>
        public static void Generate(AssetCatalog catalog, string savePath)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by AssetBundle Packer. Do not modify.");
            sb.AppendLine("public static class AssetKeys");
            sb.AppendLine("{");

            foreach (var key in catalog.AssetKeys)
            {
                var originalKey = key; // 原始资源路径（可能大小写混合）
                var memberName = ConvertToPascalCase(originalKey);
                sb.AppendLine($"    public const string {memberName} = \"{key}\";");
            }

            sb.AppendLine("}");
            
            // 确保目录存在
            Directory.CreateDirectory(Path.GetDirectoryName(savePath));
            File.WriteAllText(savePath, sb.ToString());
            AssetDatabase.Refresh();
        }

        /// <summary>
        /// 将资源路径转换为合法的 C# 标识符（驼峰命名）
        /// </summary>
        private static string ConvertToPascalCase(string assetPath)
        {
            // 去掉扩展名，只留文件名（若需要目录，可自行拼接）
            var fileName = Path.GetFileNameWithoutExtension(assetPath);

            fileName = fileName.Replace('.', '_').Replace(' ', '_').Replace('-', '_');
            
            // 按下划线切分
            var words = fileName.Split('_', StringSplitOptions.RemoveEmptyEntries);
    
            var sb = new StringBuilder();
            for (var i = 0; i < words.Length; i++)
            {
                if (words[i].Length > 0)
                {
                    sb.Append(char.ToUpperInvariant(words[i][0]));
                    if (words[i].Length > 1)
                        sb.Append(words[i].Substring(1).ToLowerInvariant());
                    
                    if(i < words.Length - 1)
                        sb.Append("_");
                }
            }
    
            var result = sb.ToString();
            // 若首字符是数字，加下划线前缀
            if (result.Length > 0 && char.IsDigit(result[0]))
                result = $"_{result}";
        
            return result;
        }
    }
}
