using System.Collections.Generic;
using System.IO;
using System.Text;
using Core.AssetBundles.Management;
using UnityEditor;

namespace Editor.AssetBundle.Core
{
    /// <summary>
    /// AB包名常量生成器
    /// </summary>
    public static class AssetBundleKeyGenerator
    {
        public static void Generate(AssetCatalog catalog, string savePath)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by AssetBundle Packer. Do not modify.");
            sb.AppendLine("public static class AssetBundleKeys");
            sb.AppendLine("{");

            foreach (var bundleName in catalog.ABPackageCollection.Keys)
            {
                // 去掉 .assetBundle 后缀，转换为合法标识符
                var rawName = Path.GetFileNameWithoutExtension(bundleName);
                var memberName = ConvertToPascalCase(rawName);
                
                // 可根据需要区分场景包（例如加前缀 Scene_）
                // 这里简单处理，直接使用包名
                sb.AppendLine($"    public const string {memberName} = \"{bundleName}\";");
            }

            sb.AppendLine("}");
            
            Directory.CreateDirectory(Path.GetDirectoryName(savePath));
            File.WriteAllText(savePath, sb.ToString());
            AssetDatabase.Refresh();
        }

        private static string ConvertToPascalCase(string name)
        {
            // 与 AssetKeyGenerator 相同的命名转换逻辑
            var words = name.Split('_', System.StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();
            foreach (var word in words)
            {
                if (word.Length > 0)
                {
                    sb.Append(char.ToUpperInvariant(word[0]));
                    if (word.Length > 1)
                        sb.Append(word.Substring(1).ToLowerInvariant());
                }
            }
            var result = sb.ToString();
            // 避免出现首个字符出现非法字符
            if (result.Length > 0 && char.IsDigit(result[0]))
                result = $"_{result}";
            return result;
        }
        
        public static void GenerateFromNames(IEnumerable<string> bundleNames, string savePath)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by AssetBundle Packer. Do not modify.");
            sb.AppendLine("public static class AssetBundleKeys");
            sb.AppendLine("{");

            foreach (var name in bundleNames)
            {
                string memberName = ConvertToPascalCase(name);
                sb.AppendLine($"    public const string {memberName} = \"{name}\";");
            }

            sb.AppendLine("}");
    
            Directory.CreateDirectory(Path.GetDirectoryName(savePath));
            File.WriteAllText(savePath, sb.ToString());
        }
    }
}